services:
  postgres:
    image: postgres:15
    container_name: nbta_prod_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: adonis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: nbta_prod_pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: nbta_prod_minio
    ports:
      - '9000:9000'
      - '8900:8900'
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio:/data
    command: 'minio server /data/minio --console-address ":8900"'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nbta_prod_api
    ports:
      - "3333:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://adonis:secret@nbta_prod_db:5432/adonis_db"
      MINIO_ENDPOINT: "nbta_prod_minio"
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio:
    driver: local
