version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nbta_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: adonis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: nbta_minio
    ports:
      - '9000:9000'
      - '8900:8900'
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio:/data
    command: 'minio server /data/minio --console-address ":8900"'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nbta_api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://adonis:secret@nbta_db:5432/adonis_db"
      MINIO_ENDPOINT: "http://nbta_minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio:
    driver: local
