services:
  - type: web
    name: NothingBetterThanAL
    runtime: node
    region: frankfurt
    plan: free
    branch: feature/stats
    buildCommand: node install
    startCommand: node ace serve --hmr
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: NothingBetterThanAL
          property: connectionString

databases:
  - name: NothingBetterThanAL
    region: frankfurt
    plan: free
